services:
  backend:
    build: ./back
    container_name: ethr-test-back
    ports:
      - "33002:3000"
    volumes:
      - ./back:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - ethr-net

  frontend:
    build: ./front
    container_name: ethr-test-front
    ports:
      - "33001:3000"
    volumes:
      - ./front:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - ethr-net

  eip4437:
    build: ./EIP-4437
    container_name: ethr-test-eip4437
    ports:
      - "38545:8545"
    volumes:
      - ./EIP-4437:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    networks:
      - ethr-net
    stdin_open: true
    tty: true

networks:
  ethr-net:
    driver: bridge
